In [6]:
import pandas as pd

In [10]:
df2 = pd.read_csv("merged_features_IC50_gtpase_kras.csv")
df2

,ChEMBL ID,Smiles,FC,N,H,Cl,Br,I,P,F,...,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,Standard Value
0,CHEMBL5428861,C[C@H](Oc1nc2c(F)c(-c3cccc(Cl)c3Cl)c(CCC#N)cc2...,0,368,37,2,0,0,0,1,...,0,0,0,0,0,0,0,0,0,100.0
1,CHEMBL5428861,C[C@H](Oc1nc2c(F)c(-c3cccc(Cl)c3Cl)c(CCC#N)cc2...,0,368,37,2,0,0,0,1,...,0,0,0,0,0,0,0,0,0,100.0
2,CHEMBL5207895,C=Cc1ncc2n1CCN(c1nc(=O)n(CC3CC3)c3nc(-c4c(O)cc...,0,248,22,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,100.0
3,CHEMBL5207895,C=Cc1ncc2n1CCN(c1nc(=O)n(CC3CC3)c3nc(-c4c(O)cc...,0,248,22,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,5000.0
4,CHEMBL3218637,CC1(C)COC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCCNC...,0,734,92,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843,CHEMBL4456598,C=CC(=O)N1CCN(c2nc(OC[C@@H]3CCCN3C)nc3c2CCN(c2...,0,282,36,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,48.0
1844,CHEMBL4456598,C=CC(=O)N1CCN(c2nc(OC[C@@H]3CCCN3C)nc3c2CCN(c2...,0,282,36,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,142.0
1845,CHEMBL5077861,C=CC(=O)N1CC2(CC(n3nc(-c4ccc5c(cnn5C)c4)c(-c4c...,0,276,28,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,20.0
1846,CHEMBL5077861,C=CC(=O)N1CC2(CC(n3nc(-c4ccc5c(cnn5C)c4)c(-c4c...,0,276,28,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,444.0
1847,CHEMBL5077861,C=CC(=O)N1CC2(CC(n3nc(-c4ccc5c(cnn5C)c4)c(-c4c...,0,276,28,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17.0

In [11]:
import numpy as np
import pandas as pd
def pIC50(input):
    pIC50 = []

    input["Standard Value"] = pd.to_numeric(input["Standard Value"],errors='coerce')

    for i in input["Standard Value"]:
        molar = i*(10**-9) # Converts nM to M
        pIC50.append(-np.log10(molar))

    input['pIC50'] = pIC50
    x = input["pIC50"]

    return x

In [12]:
filename = "merged_features_IC50_gtpase_kras.csv"
#df = pd.read_csv("fda_original.csv",sep=";")
df2 = pd.read_csv(filename)
df2.dropna(subset=['Standard Value'], inplace=True)
df2['Standard Value'] = pIC50(df2)
df2['Standard Value'] = df2['pIC50']  # Replace 'SV' column with pIC50 values

# Drop 'pIC50' column (optional) as it's now redundant
df2.drop(columns=['pIC50'], inplace=True)

df2

,ChEMBL ID,Smiles,FC,N,H,Cl,Br,I,P,F,...,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,Standard Value
0,CHEMBL5428861,C[C@H](Oc1nc2c(F)c(-c3cccc(Cl)c3Cl)c(CCC#N)cc2...,0,368,37,2,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.000000
1,CHEMBL5428861,C[C@H](Oc1nc2c(F)c(-c3cccc(Cl)c3Cl)c(CCC#N)cc2...,0,368,37,2,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.000000
2,CHEMBL5207895,C=Cc1ncc2n1CCN(c1nc(=O)n(CC3CC3)c3nc(-c4c(O)cc...,0,248,22,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,7.000000
3,CHEMBL5207895,C=Cc1ncc2n1CCN(c1nc(=O)n(CC3CC3)c3nc(-c4c(O)cc...,0,248,22,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,5.301030
4,CHEMBL3218637,CC1(C)COC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCCNC...,0,734,92,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5.744727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843,CHEMBL4456598,C=CC(=O)N1CCN(c2nc(OC[C@@H]3CCCN3C)nc3c2CCN(c2...,0,282,36,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7.318759
1844,CHEMBL4456598,C=CC(=O)N1CCN(c2nc(OC[C@@H]3CCCN3C)nc3c2CCN(c2...,0,282,36,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6.847712
1845,CHEMBL5077861,C=CC(=O)N1CC2(CC(n3nc(-c4ccc5c(cnn5C)c4)c(-c4c...,0,276,28,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7.698970
1846,CHEMBL5077861,C=CC(=O)N1CC2(CC(n3nc(-c4ccc5c(cnn5C)c4)c(-c4c...,0,276,28,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6.352617
1847,CHEMBL5077861,C=CC(=O)N1CC2(CC(n3nc(-c4ccc5c(cnn5C)c4)c(-c4c...,0,276,28,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7.769551

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Load training descriptors data
#df1 = df1.loc[:, ~df1.columns.str.contains('Unnamed')]
df2.dropna(subset=['Standard Value'], inplace=True)
X = df2.drop(columns=['Standard Value','Smiles'])
y = df2['Standard Value']

# Initialize model and pipeline
model = RandomForestRegressor(max_depth=20, min_samples_leaf=10)
pipe = Pipeline([('scaler', StandardScaler()), ('model', model)])

# Load new descriptors data
new_descriptors = pd.read_csv('FDA_Hyb_Features.csv')
new_descriptors.dropna(inplace=True)

# Extract ChEMBL IDs and SMILES
chembl_id_column = new_descriptors['ChEMBL ID']
smiles_column = new_descriptors['Smiles']
new_descriptors.drop(columns=['ChEMBL ID', 'Smiles'], inplace=True)

# Ensure new_descriptors has the same columns as X
missing_cols = set(X.columns) - set(new_descriptors.columns)  # Columns missing in new data
extra_cols = set(new_descriptors.columns) - set(X.columns)  # Extra columns in new data

# Add missing columns with zero values
for col in missing_cols:
    new_descriptors[col] = 0

# Drop extra columns
new_descriptors = new_descriptors[X.columns]  # Reorder and drop extras

# Now X and new_descriptors have identical columns

# Initialize a DataFrame to store results
loop_results_df = pd.DataFrame(columns=['ChEMBL ID', 'Smiles', 'Predicted Value'])

# Number of iterations
loop_n = 50

# Dictionary to store predicted values for each ChEMBL ID
predicted_values = {chembl_id: [] for chembl_id in chembl_id_column.unique()}

# Run the loop to fit the model and predict the values
for i in range(loop_n):
    pipe.fit(X, y)

    loop_predicted_values = pipe.predict(new_descriptors)

    loop_df = pd.DataFrame({
        'ChEMBL ID': chembl_id_column,
        'Smiles': smiles_column,
        'Predicted Value': loop_predicted_values
    })
    loop_df.sort_values(by='Predicted Value', ascending=False, inplace=True)

    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=FutureWarning)
        loop_results_df = pd.concat([loop_results_df, loop_df.head(30)])

    # Store the predicted values for each ChEMBL ID
    for chembl_id, predicted_value in zip(chembl_id_column, loop_predicted_values):
        if chembl_id in predicted_values:
            predicted_values[chembl_id].append(predicted_value)

# Calculate frequency of each ChEMBL ID in the top 10
value_counts = loop_results_df['ChEMBL ID'].value_counts(normalize=True) * 10
#print(value_counts)

# Get the top 13 ChEMBL IDs
top_30_chembl_ids = value_counts.head(30).index

In [10]:
mean_values = {chembl_id: np.mean(predicted_values[chembl_id]) for chembl_id in top_30_chembl_ids}
std_dev_values = {chembl_id: np.std(predicted_values[chembl_id]) for chembl_id in top_30_chembl_ids}

summary_df = pd.DataFrame({
    'ChEMBL ID': top_30_chembl_ids,
    'Frequency': [value_counts[chembl_id] for chembl_id in top_30_chembl_ids],
    'Avg Predicted Value': [mean_values[chembl_id] for chembl_id in top_30_chembl_ids]
})

summary_df.head(30)

        ChEMBL ID  Frequency  Avg Predicted Value
0   CHEMBL4594350   0.333333             7.868301
1   CHEMBL4559134   0.333333             7.111368
2      CHEMBL1280   0.333333             7.095846
3   CHEMBL2361370   0.333333             7.620747
4   CHEMBL5095049   0.333333             7.123404
5   CHEMBL2103744   0.333333             7.182268
6   CHEMBL3183409   0.333333             7.242201
7   CHEMBL4297091   0.333333             7.323728
8   CHEMBL3989958   0.333333             7.508900
9   CHEMBL3187985   0.333333             7.451993
10  CHEMBL3707183   0.333333             7.558675
11  CHEMBL2359966   0.333333             7.558665
12  CHEMBL2105735   0.326667             7.085479
13  CHEMBL1082407   0.313333             7.029242
14  CHEMBL2364637   0.313333             7.007935
15  CHEMBL3989694   0.306667             7.064413
16  CHEMBL2106615   0.300000             7.012389
17  CHEMBL3707246   0.293333             6.972922
18  CHEMBL1200781   0.286667             6.949686
19  CHEMBL4594273   0.260000             6.933375
20  CHEMBL1615374   0.233333             6.915989
21     CHEMBL1339   0.233333             6.940281
22     CHEMBL1668   0.220000             6.907257
23  CHEMBL1738797   0.220000             6.928855
24     CHEMBL1708   0.200000             6.913309
25   CHEMBL439849   0.193333             6.886007
26  CHEMBL3707320   0.180000             6.897293
27  CHEMBL2448613   0.180000             6.897965
28  CHEMBL3301603   0.166667             6.892684
29  CHEMBL1908370   0.146667             6.867046